version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_vuelos
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=AdminVuelos2026!
    ports:
      - "1433:1433"
    restart: unless-stopped