version: '3.8'

services:
  # motor de base de datos SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_vuelos
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=AdminVuelos2026!
    ports:
      - "1433:1433"
    restart: unless-stopped

  # contenedor para inicializar la base de datos
  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_init
    depends_on:
      - sqlserver
    volumes:
      - ./db.sql:/db.sql
    command: /bin/bash -c "sleep 15 && /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P 'AdminVuelos2026!' -C -i /db.sql"